### ISSUE TITLE
USB 2.0 doesn't work on Orange Pi 5

### ISSUE THREAD

**Issue by GongTae** [kwankiu/archlinux-installer-rock5#28]
I was trying to connect a wireless mouse through port 2.0, and it receives no signal.

**Comment by kwankiu** [comment]
Which kernel option did you choose during installation?
Is keyboard working through USB 2.0?

**Comment by GongTae** [comment]
I chose the Joshua kernel, it works fine on USB 3.0.

**Comment by kwankiu** [comment]
> I chose the Joshua kernel, it works fine on USB 3.0.

Does the same issue happens on Joshua’s Ubuntu image or does this issue only happen on Joshua’s kernel (like does this happen if you choose linux-aarch64-rockchip-orangepi ?)

If yes, you may want to open an issue at
https://github.com/Joshua-Riek/linux-rockchip

**Comment by GongTae** [comment]
The problem does not exist when I use Ubuntu-Joshua, or when I use archlinux-7ji. (the problem with said USB2.0 port sharing the line with the USB-C port was present in the installer as well)

**Comment by GongTae** [comment]
The problem still existing on release "b06"

**Comment by GongTae** [comment]
To solve this, I used this file [https://github.com/Joshua-Riek/ubuntu-rockchip/blob/main/overlay/usr/lib/systemd/system/enable-usb2.service]
And I put it in the path: `/usr/lib/systemd/system/`
The next step was to activate the service with:
`sudo systemctl enable enable-usb2`
and start it with:
`sudo systemctl start enable-usb2`

**Comment by kwankiu** [comment]
> To solve this, I used this file [https://github.com/Joshua-Riek/ubuntu-rockchip/blob/main/overlay/usr/lib/systemd/system/enable-usb2.service] And I put it in the path: `/usr/lib/systemd/system/` The next step was to activate the service with: `sudo systemctl enable enable-usb2` and start it with: `sudo systemctl start enable-usb2`

Thank you for the information, I will add this fix soon.
