### ISSUE TITLE
CuteFish DE - Audio problem..

### ISSUE THREAD

**Issue by DarkevilPT** [kwankiu/archlinux-installer-rock5#31]
https://github.com/kwankiu/archlinux-installer-rock5/assets/3583885/db739f12-c79e-4896-8d3c-0b9e1455753f

![20240318_231310](https://github.com/kwankiu/archlinux-installer-rock5/assets/3583885/023cb6b9-e95d-4595-9b76-bbfc1be32145)

Theres no audio options
Bt barely connects my JBL speaker (it kinda does but) doesnt stays connected probably due to the audio problem.

**Comment by kwankiu** [comment]
seems like issues with Cutefish DE itself.
