### ISSUE TITLE
Installer Issues - Mainline 6.8.x

### ISSUE THREAD

**Issue by DarkevilPT** [kwankiu/archlinux-installer-rock5#35]
![20240402_150924](https://github.com/kwankiu/archlinux-installer-rock5/assets/3583885/0e343d27-ecae-413d-89ed-bdeb1a5d6f01)

Icons apps... useless... Broke big son.
I selected the mainline image 6.8.x

**Comment by DarkevilPT** [comment]
![20240402_152924](https://github.com/kwankiu/archlinux-installer-rock5/assets/3583885/4b0c5211-8b23-4481-a562-2fbb1fa63c86)
Gnome Full after the reboot...

Also the last final prompt 'Installation complete you can reboot now (y/n)? doesnt even waits for me to type y and just reboots..

**Comment by DarkevilPT** [comment]
https://github.com/kwankiu/archlinux-installer-rock5/assets/3583885/2bb0584a-95d1-4e9c-9e05-eae17d431a5a

Noice.

**Comment by DarkevilPT** [comment]
didnt eray helped you ? fake sake mate... erayg? where is that big dev about? 😔 if I dont care you will keep it broken 😀 what will u tell me to do next? 'doesnt matter use gnome full' whats next ? kda plasma ? kek..

**Comment by DarkevilPT** [comment]
![20240402_153955](https://github.com/kwankiu/archlinux-installer-rock5/assets/3583885/7e98ee1d-1f8f-4ec1-967d-c67eb012d8a2)

**Comment by kwankiu** [comment]
> didnt eray helped you ? fake sake mate... erayg? where is that big dev about? 😔 if I dont care you will keep it broken 😀 what will u tell me to do next? 'doesnt matter use gnome full' whats next ? kda plasma ? kek..

Nope ... Hmm, Idk what is changed in Gnome 46, so that this Arch Linux ARM updates broke Gnome completely for new installations

**Comment by DarkevilPT** [comment]
Then this sucks.. we cant rely on the installer thanks to the fucking arch linux... only on unmantained images.. like BredOS... this is frustating and disapointing..
